# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19_zvKKPXINmaWOA9Zd819LugJQRk64JN
"""

from google.colab import drive
drive.mount('/content/drive')

!cd drive/MyDrive/hopfield

from PIL import Image, ImageFont
from random import randint
import numpy as np
from hopfield import hopfield 

# create img:
font_siza = 16
font = ImageFont.truetype("tahoma.ttf", font_siza)

for char in "ABCDEFGHIJ":
    im = Image.Image()._new(font.getmask(char))
    im.save("train/16/" + char + ".bmp")

font_siza = 32
font = ImageFont.truetype("tahoma.ttf", font_siza)

for char in "ABCDEFGHIJ":
    im = Image.Image()._new(font.getmask(char))
    im.save("train/32/" + char + ".bmp")

font_siza = 64
font = ImageFont.truetype("tahoma.ttf", font_siza)

for char in "ABCDEFGHIJ":
    im = Image.Image()._new(font.getmask(char))
    im.save("train/64/" + char + ".bmp")

# create noisy img:
font_siza = 16
font = ImageFont.truetype("tahoma.ttf", font_siza)

for char in "ABCDEFGHIJ":
    im = Image.Image()._new(font.getmask(char))
    data = np.array(im)
    for i in data:
        for j in range(len(i)):
            r = randint(1, 10)
            if r <= 1:
                i[j] = 0
                rescaled = (255.0 / data.max() *
                            (data - data.min())).astype(np.uint8)
                im = Image.fromarray(rescaled)
                im.save("train/16/" + char + ".bmp")

font_siza = 32
font = ImageFont.truetype("tahoma.ttf", font_siza)

for char in "ABCDEFGHIJ":
    im = Image.Image()._new(font.getmask(char))
    data = np.array(im)
    for i in data:
        for j in range(len(i)):
            r = randint(1, 10)
            if r <= 3:
                i[j] = 0
                rescaled = (255.0 / data.max() *
                            (data - data.min())).astype(np.uint8)
                im = Image.fromarray(rescaled)
                im.save("train/32/" + char + ".bmp")

font_siza = 64
font = ImageFont.truetype("tahoma.ttf", font_siza)

for char in "ABCDEFGHIJ":
    im = Image.Image()._new(font.getmask(char))
    data = np.array(im)  # "data" is a height x width x 4 numpy array
    for i in data:
        for j in range(len(i)):
            r = randint(1, 10)
            if r <= 6:
                i[j] = 0
                rescaled = (255.0 / data.max() *
                            (data - data.min())).astype(np.uint8)
                im = Image.fromarray(rescaled)
                im.save("train/64/" + char + ".bmp")


current_path = '/content/drive/My Drive/hopfield'
train_paths = []
path = "train/64/"
for i in "ABCDEFGHIJ":
    train_paths.append(path + i + ".bmp")

test_paths = []
path = "test/64/"
for i in "ABCDEFGHIJ":
    test_paths.append(path + i + ".bmp")

hopfield(train_files=train_paths, test_files=test_paths, theta=0.5, time=20000, size=(100, 100), threshold=60, current_path=current_path)